### PR TITLE
Emergency downgrade script + procedure

### PR DESCRIPTION
**Pull request by jzu**

### CODE REVIEW

**Comment by cgcardona** [comment]
This looks good to me. @jpop32 thoughts?

**Comment by jpop32** [comment]
Talked it over with Dan, and though this is a fine solution, it might be better to merge it into the existing installer script. So we'll use this approach and just add it to the other script.

**Comment by cgcardona** [comment]
@jpop32 can you handle merging this into an existing script and creating a new PR?

**Comment by jpop32** [comment]
Yep, will do.

**Comment by jpop32** [comment]
Added downgrade functionality to the installer script #139.

Thanks @jzu for the inspiration. Also pilfered parts of your script. :-) Credited in the tutorial, of course.

**Pull request closed without merging**
