### PR TITLE
Add chain-config-content usage example

### PR DESCRIPTION
**Pull request by lebdron**
Resolves https://github.com/ava-labs/avalanchego/issues/1069

### CODE REVIEW

**Comment by laviniat1996** [comment]
@lebdron 
Can you please add the translation to `i18n/es/docusaurus-plugin-content-docs/current/nodes/configure/avalanchego-config-flags.md` . Just replace the old text with this:

Ejemplo:

```bash
cchainconfig="$(echo -n '{"log-level":"trace"}' | base64)"
chainconfig="$(echo -n "{\"C\":{\"Config\":\"${cchainconfig}\",\"Upgrade\":null}}" | base64)"
avalanchego --chain-config-content "${chainconfig}"
```

**Comment by lebdron** [comment]
@laviniat1996 Done, thanks!

**Comment by meaghanfitzgerald** [comment]
please address markdownlint issues 
https://github.com/ava-labs/avalanche-docs/blob/master/style-checker-notes.md#markdownlint

**Comment by lebdron** [comment]
@meaghanfitzgerald @laviniat1996 Done.

**Review by laviniat1996 — APPROVED** [review]

**Pull request merged**
