### PR TITLE
Reorganize Stateful Precompile Docs

### PR DESCRIPTION
**Pull request by RodrigoVillar**
## Why this should be merged

Currently, the documentation about stateful precompiles is contained in one entire webpage. Given that the process of creating a stateful precompile from scratch is complex, this results in a extremely verbose webpage which is extremely hard to read, for both experienced and new developers alike. This PR fixes this by splitting up the stateful precompile page into multiple sections.

## How this works

Whenever possible, I identified similar blocks of documentation within the original page and delegated it to its own section/webpage.

## How these changes were tested 

I ran `yarn start` on my local machine to confirm my changes were what I expected them to be.

## To prevent any errors while building

- [] run `vale /docs/file/path` on all changed `.md` files to ensure all grammar rules pass
- [] run `markdownlint /docs/file/path` on all changed `.md` files to ensure all linting rules pass
- [] complete the above two checks and all additional rules outlined in `style-checker-notes.md` to
  ensure all checks pass

### If a document was removed/deleted

- [] the path to that doc must be redirected to a valid URL via the
  `_redirects` file
- [] `_redirects` were manually verified with the cloudflare preview link
- [] `sidebars.json` reflects all changes made to file path

### If a document was moved

- [] all files that were moved from their current directory to a new path have had their paths
  redirected via the `_redirects` file
- [] `_redirects` were manually verified with the cloudflare preview link
- [] `sidebars.json` reflects all changes made to file path

### CODE REVIEW

**Comment by RodrigoVillar** [comment]
@meaghanfitzgerald redirects haven't been updated in my PR

**Comment by ashucoder9** [comment]
We need to do a few things here:

1. Run the translate GT command to translate all the modified/new files
2. Ensure that deleted files are not present in the translated version
3. Ensure translated content doesn't break the build process
4. You must edit the redirect file with the links at the bottom, don't forget to include the Spanish redirect link.

Gonna run the translate command now.

**Comment by ashucoder9** [comment]
Closing this PR, more updates here: https://github.com/ava-labs/avalanche-docs/pull/1599

**Comment by ashucoder9** [comment]
Closing this PR, more updates here: https://github.com/ava-labs/avalanche-docs/pull/1599

**Pull request closed without merging**
