### PR TITLE
Add page 'Create a simple vm from scratch using C#'

### PR DESCRIPTION
**Pull request by boulix3**

### CODE REVIEW

**Review by cgcardona — CHANGES_REQUESTED** [review]
Thanks again for your work! Here are a few requested changes.

1. Merge the latest from `master` and fix any conflicts
2. Remove the C# content and only have it in [the 1298 PR](https://github.com/ava-labs/avalanche-docs/pull/1298)
3. Remove the new dependency from `package.json` and remove the new `yarn.lock` file.

**Review by cgcardona — CHANGES_REQUESTED** [review]
Thanks for your work! Some requested changes:

1. Merge the latest from `master` into this branch and resolve any conflicts
2. Remove the `create-a-simple-vm-from-scratch.md` file and remove the link from the sidebar
3. I'm not 100% sold on the `docusaurus-theme-github-codeblock` plugin. My concern is that when the referenced files change, in their respective github repos, the corresponding snippets will become out-of-date in this tutorial. It might be wiser to hardcode the snippets.

If we remove the plugin then we'll need to update `package.json` and remove the updated `yarn.lock`.

**Comment by boulix3** [comment]
> Thanks for your work! Some requested changes:
> 
> 1. Merge the latest from `master` into this branch and resolve any conflicts
> 2. Remove the `create-a-simple-vm-from-scratch.md` file and remove the link from the sidebar
> 3. I'm not 100% sold on the `docusaurus-theme-github-codeblock` plugin. My concern is that when the referenced files change, in their respective github repos, the corresponding snippets will become out-of-date in this tutorial. It might be wiser to hardcode the snippets.
> 
> If we remove the plugin then we'll need to update `package.json` and remove the updated `yarn.lock`.

Hello, regarding the `docusaurus-theme-github-codeblock` plugin, can you check the issue #1072? This is the reason why I used it in the first place.

**Comment by boulix3** [comment]
> Thanks for your work! Some requested changes:
> 
> 1. Merge the latest from `master` into this branch and resolve any conflicts
> 2. Remove the `create-a-simple-vm-from-scratch.md` file and remove the link from the sidebar
> 3. I'm not 100% sold on the `docusaurus-theme-github-codeblock` plugin. My concern is that when the referenced files change, in their respective github repos, the corresponding snippets will become out-of-date in this tutorial. It might be wiser to hardcode the snippets.
> 
> If we remove the plugin then we'll need to update `package.json` and remove the updated `yarn.lock`.

Requested changes are done and squashed to a single commit to clean-up the history.

**Comment by boulix3** [comment]
Hello, @meaghanfitzgerald, why did you close this PR without any comment?

**Pull request closed without merging**
