### PR TITLE
Update rpc-providers.md

### PR DESCRIPTION
**Pull request by yunseonna**
Proposing to update additional possible public RPC endpoint powered by All That Node.

# Docs PR Template

## Why this should be merged

Proposing to update additional possible public RPC endpoint powered by All That Node.

## How this works

Just endpoints and links about new features

## How these changes were tested 

<please give a thorough description of how to view the changes and how they were tested>

## To prevent any errors while building

- [] run `vale /docs/file/path` on all changed `.md` files to ensure all grammar rules pass
- [] run `markdownlint /docs/file/path` on all changed `.md` files to ensure all linting rules pass
- [] complete the above two checks and all additional rules outlined in `style-checker-notes.md` to
  ensure all checks pass

### If a document was removed/deleted

- [] the path to that doc must be redirected to a valid URL via the
  `_redirects` file
- [] `_redirects` were manually verified with the cloudflare preview link
- [] `sidebars.json` reflects all changes made to file path

### If a document was moved

- [] all files that were moved from their current directory to a new path have had their paths
  redirected via the `_redirects` file
- [] `_redirects` were manually verified with the cloudflare preview link
- [] `sidebars.json` reflects all changes made to file path

### CODE REVIEW

**Comment by laviniat1996** [comment]
@yunseonna Hi, can you please address the failed checks?

**Comment by yunseonna** [comment]
@laviniat1996 
I received the following error: "Error: reviewdog exited with status code: 1."  in the Cl/ runner/vale (pull_request) .

Could you explain why it failed and how I can fix it?

**Comment by laviniat1996** [comment]
@yunseonna the vale checker just didn't like some words, so I turned it off for some lines. All checks pass now, so merging this! thank you for contributing

**Review by laviniat1996 — APPROVED** [review]

**Comment by yunseonna** [comment]
Hi @laviniat1996 

Thank you for your responses. I just noticed that the service name is incorrectly entered. Could you please change it from "All That Nodes" to "All That Node"?

Thank you!

**Pull request merged**
