### PR TITLE
Remove Avalanche Wallet references

### PR DESCRIPTION
**Pull request by laviniat1996**
Closed PR #1595 due to some conflicts This PR is up to date, with all the comments from the previous PR solved,

### CODE REVIEW

**Comment by laviniat1996** [comment]
/gt docs/nodes/validate/add-a-validator.md i18n/es/docusaurus-plugin-content-docs/current/nodes/validate/add-a-validator.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/deploy/mainnet-subnet.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/deploy/mainnet-subnet.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/deploy/fuji-testnet-subnet.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/deploy/fuji-testnet-subnet.md spanish

**Comment by laviniat1996** [comment]
@meaghanfitzgerald @ashucoder9

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/deploy/fuji-testnet-subnet.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/deploy/fuji-testnet-subnet.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/fuji-workflow.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/fuji-workflow.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/deploy/fuji-testnet-subnet.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/deploy/fuji-testnet-subnet.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/deploy/mainnet-subnet.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/deploy/mainnet-subnet.md spanish

**Comment by laviniat1996** [comment]
/gt docs/nodes/validate/add-a-validator.md i18n/es/docusaurus-plugin-content-docs/current/nodes/validate/add-a-validator.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/deploy/mainnet-subnet.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/deploy/mainnet-subnet.md spanish

**Review by dubrado — APPROVED** [review]

**Pull request merged**
