### PR TITLE
Add Coupon Info to Faucet Instructions

### PR DESCRIPTION
**Pull request by laviniat1996**
Adding additional info on how to request Fuji tokens from faucet. Users who don't have a mainnet balance of avax need to request a coupon now.

### CODE REVIEW

**Comment by laviniat1996** [comment]
i18n/es/docusaurus-plugin-content-docs/current/build/dapp/fuji-workflow.md

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/fuji-workflow.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/fuji-workflow.md

**Comment by laviniat1996** [comment]
/gpt-translate docs/build/dapp/fuji-workflow.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/fuji-workflow.md

**Comment by laviniat1996** [comment]
/gpt-translate docs/build/dapp/fuji-workflow.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/fuji-workflow.md spanish

**Comment by laviniat1996** [comment]
/gpt-translate [docs/build/dapp/fuji-workflow.md] [i18n/es/docusaurus-plugin-content-docs/current/build/dapp/fuji-workflow.md] [spanish]

**Comment by laviniat1996** [comment]
/gpt-translate /docs/build/dapp/fuji-workflow.md /i18n/es/docusaurus-plugin-content-docs/current/build/dapp/fuji-workflow.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/fuji-workflow.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/fuji-workflow.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/launch-dapp.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/launch-dapp.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/smart-contracts/erc-20.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/smart-contracts/erc-20.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/smart-contracts/get-funds-faucet.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/smart-contracts/get-funds-faucet.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/smart-contracts/nfts/deploy-collection.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/smart-contracts/nfts/deploy-collection.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/smart-contracts/remix-deploy.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/smart-contracts/remix-deploy.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/deploy/fuji-testnet-subnet.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/deploy/fuji-testnet-subnet.md

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/utility/avalanche-subnet-faucet.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/utility/avalanche-subnet-faucet.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/utility/cross-chain-evm-bridge.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/utility/cross-chain-evm-bridge.md spanish

**Comment by laviniat1996** [comment]
/gt docs/learn/avalanche/fuji.md i18n/es/docusaurus-plugin-content-docs/current/learn/avalanche/fuji.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/launch-dapp.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/launch-dapp.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/utility/avalanche-subnet-faucet.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/utility/avalanche-subnet-faucet.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/subnet/utility/cross-chain-evm-bridge.md i18n/es/docusaurus-plugin-content-docs/current/build/subnet/utility/cross-chain-evm-bridge.md spanish

**Comment by laviniat1996** [comment]
/gt docs/tooling/avalanchejs-guides/cross-chain-transfers.md i18n/es/docusaurus-plugin-content-docs/current/tooling/avalanchejs-guides/cross-chain-transfers.md  spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/smart-contracts/erc-20.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/smart-contracts/erc-20.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/smart-contracts/nfts/deploy-collection.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/smart-contracts/nfts/deploy-collection.md spanish

**Comment by laviniat1996** [comment]
/gt docs/build/dapp/smart-contracts/toolchains/foundry.md i18n/es/docusaurus-plugin-content-docs/current/build/dapp/smart-contracts/toolchains/foundry.md spanish

**Review by dubrado — APPROVED** [review]

**Pull request merged**
