### PR TITLE
Removing Mixed Query Flags

### PR DESCRIPTION
**Pull request by joshua-kim**
As part of https://github.com/ava-labs/avalanchego/pull/1428 we are removing mixed queries, so the corresponding configs can be removed.

### CODE REVIEW

**Review by danlaine — APPROVED** [review]

**Comment by danlaine** [comment]
Shouldn't be merged until avalanchego v1.10.3 is released

**Comment by meaghanfitzgerald** [comment]
ty! lgtm will approve and merge at the next release

**Comment by meaghanfitzgerald** [comment]
@danlaine @joshua-kim are there any other changes that should be made here given today's release?

**Comment by joshua-kim** [comment]
> @danlaine @joshua-kim are there any other changes that should be made here given today's release?

There's a few I believe but they're not related to this PR. I think we did change a few things in the latest release (e.g `staking-enabled` -> `sybil-protection-enabled` but we can chat about it offline.

**Review by meaghanfitzgerald — APPROVED** [review]

**Pull request merged**
