### PR TITLE
Banff serializations

### PR DESCRIPTION
**Pull request by cgcardona**
* `RemoveSubnetValidatorTx`
* `TransformSubnetTx`
* `AddPermissionlessValidatorTx`
* `AddPermissionlessDelegatorTx`
* `Proof of Possession`

### CODE REVIEW

**Review by Lizy87 — APPROVED** [review]
deleted

**Comment by Lizy87** [comment]
Thanks for the help

**Review by Lizy87 — APPROVED** [review]

**Comment by Lizy87** [comment]
Approve everything

**Comment by Lizy87** [comment]
> Approve everything

Thanks guys for all the help

**Review by danlaine — APPROVED** [review]

**Pull request merged**
